### ISSUE TITLE
Instead of posting long article warning, don't post anything at all.

### ISSUE THREAD

**Issue by jin** [fterh/rsg-retrivr#1]
Title

**Comment by banchan86** [comment]
Instead of posting just long article warning post Google webcache link.

**Comment by fterh** [comment]
@jin Thanks for the feedback. I've temporarily disabled posting "sorry, this post is too long...". 

@banchan86 Might implement this in the future, or better yet, collaborate with the author of sg_paywall_buster to incorporate his code into mine. Thanks for the suggestion!
