### ISSUE TITLE
Facebook links are not filtered

### ISSUE THREAD

**Issue by changhuapeng** [fterh/rsg-retrivr#14]
Hyperlinks to facebook are not filtered resulting in posts being deleted by the AutoModerator.

- https://www.reddit.com/r/singapore/comments/7nmn4k/halimah_yacob_spotted_in_kuala_lumpur_on_new/ds2v9om/
- https://www.reddit.com/r/singapore/comments/7ndrhr/budget_2018_to_be_delivered_on_feb_19/ds11u6b/

Edit: I have tested this on my end and it is working as intended.

**Comment by fterh** [comment]
Hi, I think I forgot to run a `git pull` on my AWS instance that is running this script. Oops. Have fixed it now.

Anyway, I plan to rewrite this in Javascript (to run on node.js) in the near future to make use of node's async functionality. Just a heads up that I have plans to retire the python bot in case you're working on new stuff for this :)
